version: "3"
services:

  standalone:
    image: williamyeh/json-server
    command: -p 3333 -w ./data.json
    ports:
      - "3333:3333"
    volumes:
      - ./data:/data

  influxdb:
    build:
      context: .
      dockerfile: ./perf/Dockerfile.influxdb
    ports:
      - "8086:8086"

  grafana:
    build:
      context: .
      dockerfile: ./perf/Dockerfile.grafana
    links:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - "3000:3000"

  k6:
    build: ./perf
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/jestExample_k6
    entrypoint: sh -c
    command: 
      - 'k6 run suite.js'
